# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Summary', models.CharField(max_length=2000)),
            ],
        ),
    ]
